#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check for .env files being staged
STAGED_ENV_FILES=$(git diff --cached --name-only | grep -E '^\.env(\..+)?$' | grep -v '.env.example')

if [ -n "$STAGED_ENV_FILES" ]; then
  echo "❌ Error: You are trying to commit environment files:"
  echo "$STAGED_ENV_FILES"
  echo "Please remove them from the commit or update .gitignore."
  exit 1
fi

npm run lint
